---
name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      # This action will create a release PR when regular conventional commits are pushed to main, it'll also detect if a release PR is merged and npm publish should happen
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          token: ${{ steps.app-token.outputs.token }}

      # Publish to NPM on new releases
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          cache: pnpm
          node-version: lts/*
      - name: install deps & build
        run: corepack enable && pnpm --version && pnpm install --ignore-scripts
        if: ${{ steps.release.outputs.releases_created }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      # Release Please has already incremented versions and published tags, so we just
      # need to publish all unpublished versions to NPM here
      - run: pnpm -r publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NPM_CONFIG_PROVENANCE: true
